### ISSUE TITLE
How Can I see this in realtime on screen? I can get the result only after executing detect.py.

### ISSUE THREAD

**Issue by sajithlaldev** [dongfang-steven-yang/social-distancing-monitoring#2]
This paper proposes the realtime on screen SD detection. How to run both detect.py and analyze.py simultaneouly to get the realitime result

**Comment by dongfang-steven-yang** [comment]
The real-time performance was demonstrated by evaluating the inference time for each frame. If you want to run them simultaneously, you need additional implementation.
