### ISSUE TITLE
meter_per_pixel  calculation

### ISSUE THREAD

**Issue by thanhdong18891** [dongfang-steven-yang/social-distancing-monitoring#3]
Hi @dongfang-steven-yang 
Thank you for your contribution. Recently, i have looked at your work. i am interested the way you do calibration on grand_central dataset based on floor plan of the building and landmark. but could you explain for me how can you calculate meter_per_pixel = 4.8768 / 144 ? Can you explain more how can you get these numbers ?

**Comment by sandydf** [comment]
I also confused about it, did you know the reason?
